<?php

use App\Http\Controllers\Subsonic\CreatePlaylistController;
use App\Http\Controllers\Subsonic\DeletePlaylistController;
use App\Http\Controllers\Subsonic\DownloadController;
use App\Http\Controllers\Subsonic\GetAlbumController;
use App\Http\Controllers\Subsonic\GetAlbumInfo2Controller;
use App\Http\Controllers\Subsonic\GetAlbumList2Controller;
use App\Http\Controllers\Subsonic\GetArtistController;
use App\Http\Controllers\Subsonic\GetArtistInfo2Controller;
use App\Http\Controllers\Subsonic\GetArtistsController;
use App\Http\Controllers\Subsonic\GetAvatarController;
use App\Http\Controllers\Subsonic\GetCoverArtController;
use App\Http\Controllers\Subsonic\GetGenresController;
use App\Http\Controllers\Subsonic\GetLicenseController;
use App\Http\Controllers\Subsonic\GetLyricsBySongIdController;
use App\Http\Controllers\Subsonic\GetMusicFoldersController;
use App\Http\Controllers\Subsonic\GetNowPlayingController;
use App\Http\Controllers\Subsonic\GetOpenSubsonicExtensionsController;
use App\Http\Controllers\Subsonic\GetPlaylistController;
use App\Http\Controllers\Subsonic\GetPlaylistsController;
use App\Http\Controllers\Subsonic\GetRandomSongsController;
use App\Http\Controllers\Subsonic\GetSongController;
use App\Http\Controllers\Subsonic\GetSongsByGenreController;
use App\Http\Controllers\Subsonic\GetStarred2Controller;
use App\Http\Controllers\Subsonic\GetUserController;
use App\Http\Controllers\Subsonic\PingController;
use App\Http\Controllers\Subsonic\ScrobbleController;
use App\Http\Controllers\Subsonic\Search3Controller;
use App\Http\Controllers\Subsonic\SetRatingController;
use App\Http\Controllers\Subsonic\StarController;
use App\Http\Controllers\Subsonic\StreamController;
use App\Http\Controllers\Subsonic\UnstarController;
use App\Http\Controllers\Subsonic\UpdatePlaylistController;
use App\Http\Middleware\NormalizeSubsonicArrayParams;
use App\Http\Middleware\SubsonicAuth;
use Illuminate\Support\Facades\Route;

Route::prefix('rest')
    ->middleware([NormalizeSubsonicArrayParams::class, SubsonicAuth::class])
    ->group(static function (): void {
        Route::match(['get', 'post'], 'ping.view', PingController::class);
        Route::match(['get', 'post'], 'getLicense.view', GetLicenseController::class);
        Route::match(['get', 'post'], 'getMusicFolders.view', GetMusicFoldersController::class);
        Route::match(['get', 'post'], 'getArtists.view', GetArtistsController::class);
        Route::match(['get', 'post'], 'getArtist.view', GetArtistController::class);
        Route::match(['get', 'post'], 'getAlbum.view', GetAlbumController::class);
        Route::match(['get', 'post'], 'getSong.view', GetSongController::class);
        Route::match(['get', 'post'], 'getGenres.view', GetGenresController::class);
        Route::match(['get', 'post'], 'search3.view', Search3Controller::class);
        Route::match(['get', 'post'], 'getAlbumList2.view', GetAlbumList2Controller::class);
        Route::match(['get', 'post'], 'stream.view', StreamController::class);
        Route::match(['get', 'post'], 'getCoverArt.view', GetCoverArtController::class);
        Route::match(['get', 'post'], 'getPlaylists.view', GetPlaylistsController::class);
        Route::match(['get', 'post'], 'getPlaylist.view', GetPlaylistController::class);
        Route::match(['get', 'post'], 'createPlaylist.view', CreatePlaylistController::class);
        Route::match(['get', 'post'], 'updatePlaylist.view', UpdatePlaylistController::class);
        Route::match(['get', 'post'], 'deletePlaylist.view', DeletePlaylistController::class);
        Route::match(['get', 'post'], 'scrobble.view', ScrobbleController::class);
        Route::match(['get', 'post'], 'star.view', StarController::class);
        Route::match(['get', 'post'], 'unstar.view', UnstarController::class);
        Route::match(['get', 'post'], 'setRating.view', SetRatingController::class);
        Route::match(['get', 'post'], 'getStarred2.view', GetStarred2Controller::class);
        Route::match(['get', 'post'], 'getRandomSongs.view', GetRandomSongsController::class);
        Route::match(['get', 'post'], 'getNowPlaying.view', GetNowPlayingController::class);
        Route::match(['get', 'post'], 'getUser.view', GetUserController::class);
        Route::match(['get', 'post'], 'getAvatar.view', GetAvatarController::class);
        Route::match(['get', 'post'], 'getOpenSubsonicExtensions.view', GetOpenSubsonicExtensionsController::class);
        Route::match(['get', 'post'], 'download.view', DownloadController::class);
        Route::match(['get', 'post'], 'getSongsByGenre.view', GetSongsByGenreController::class);
        Route::match(['get', 'post'], 'getLyricsBySongId.view', GetLyricsBySongIdController::class);
        Route::match(['get', 'post'], 'getArtistInfo2.view', GetArtistInfo2Controller::class);
        Route::match(['get', 'post'], 'getAlbumInfo2.view', GetAlbumInfo2Controller::class);
    });
