<?php

use App\Http\Controllers\Subsonic\CreateInternetRadioStationController;
use App\Http\Controllers\Subsonic\CreatePlaylistController;
use App\Http\Controllers\Subsonic\CreatePodcastChannelController;
use App\Http\Controllers\Subsonic\DeleteInternetRadioStationController;
use App\Http\Controllers\Subsonic\DeletePlaylistController;
use App\Http\Controllers\Subsonic\DeletePodcastChannelController;
use App\Http\Controllers\Subsonic\DownloadController;
use App\Http\Controllers\Subsonic\GetAlbumController;
use App\Http\Controllers\Subsonic\GetAlbumInfo2Controller;
use App\Http\Controllers\Subsonic\GetAlbumInfoController;
use App\Http\Controllers\Subsonic\GetAlbumList2Controller;
use App\Http\Controllers\Subsonic\GetAlbumListController;
use App\Http\Controllers\Subsonic\GetArtistController;
use App\Http\Controllers\Subsonic\GetArtistInfo2Controller;
use App\Http\Controllers\Subsonic\GetArtistInfoController;
use App\Http\Controllers\Subsonic\GetArtistsController;
use App\Http\Controllers\Subsonic\GetAvatarController;
use App\Http\Controllers\Subsonic\GetCoverArtController;
use App\Http\Controllers\Subsonic\GetGenresController;
use App\Http\Controllers\Subsonic\GetIndexesController;
use App\Http\Controllers\Subsonic\GetInternetRadioStationsController;
use App\Http\Controllers\Subsonic\GetLicenseController;
use App\Http\Controllers\Subsonic\GetLyricsBySongIdController;
use App\Http\Controllers\Subsonic\GetLyricsController;
use App\Http\Controllers\Subsonic\GetMusicDirectoryController;
use App\Http\Controllers\Subsonic\GetMusicFoldersController;
use App\Http\Controllers\Subsonic\GetNewestPodcastsController;
use App\Http\Controllers\Subsonic\GetNowPlayingController;
use App\Http\Controllers\Subsonic\GetOpenSubsonicExtensionsController;
use App\Http\Controllers\Subsonic\GetPlaylistController;
use App\Http\Controllers\Subsonic\GetPlaylistsController;
use App\Http\Controllers\Subsonic\GetPlayQueueController;
use App\Http\Controllers\Subsonic\GetPodcastsController;
use App\Http\Controllers\Subsonic\GetRandomSongsController;
use App\Http\Controllers\Subsonic\GetSongController;
use App\Http\Controllers\Subsonic\GetSongsByGenreController;
use App\Http\Controllers\Subsonic\GetStarred2Controller;
use App\Http\Controllers\Subsonic\GetStarredController;
use App\Http\Controllers\Subsonic\GetUserController;
use App\Http\Controllers\Subsonic\PingController;
use App\Http\Controllers\Subsonic\RefreshPodcastsController;
use App\Http\Controllers\Subsonic\SavePlayQueueController;
use App\Http\Controllers\Subsonic\ScrobbleController;
use App\Http\Controllers\Subsonic\Search2Controller;
use App\Http\Controllers\Subsonic\Search3Controller;
use App\Http\Controllers\Subsonic\SetRatingController;
use App\Http\Controllers\Subsonic\StarController;
use App\Http\Controllers\Subsonic\StreamController;
use App\Http\Controllers\Subsonic\UnstarController;
use App\Http\Controllers\Subsonic\UpdateInternetRadioStationController;
use App\Http\Controllers\Subsonic\UpdatePlaylistController;
use App\Http\Middleware\AuthenticateSubsonicRequests;
use App\Http\Middleware\NormalizeSubsonicArrayParams;
use Illuminate\Support\Facades\Route;

Route::prefix('rest')
    ->middleware([NormalizeSubsonicArrayParams::class, AuthenticateSubsonicRequests::class])
    ->group(static function (): void {
        Route::match(['get', 'post'], 'ping.view', PingController::class);
        Route::match(['get', 'post'], 'getLicense.view', GetLicenseController::class);
        Route::match(['get', 'post'], 'getMusicFolders.view', GetMusicFoldersController::class);
        Route::match(['get', 'post'], 'getArtists.view', GetArtistsController::class);
        Route::match(['get', 'post'], 'getIndexes.view', GetIndexesController::class);
        Route::match(['get', 'post'], 'getMusicDirectory.view', GetMusicDirectoryController::class);
        Route::match(['get', 'post'], 'getInternetRadioStations.view', GetInternetRadioStationsController::class);
        Route::match(['get', 'post'], 'createInternetRadioStation.view', CreateInternetRadioStationController::class);
        Route::match(['get', 'post'], 'updateInternetRadioStation.view', UpdateInternetRadioStationController::class);
        Route::match(['get', 'post'], 'deleteInternetRadioStation.view', DeleteInternetRadioStationController::class);
        Route::match(['get', 'post'], 'getArtist.view', GetArtistController::class);
        Route::match(['get', 'post'], 'getAlbum.view', GetAlbumController::class);
        Route::match(['get', 'post'], 'getSong.view', GetSongController::class);
        Route::match(['get', 'post'], 'getGenres.view', GetGenresController::class);
        Route::match(['get', 'post'], 'search2.view', Search2Controller::class);
        Route::match(['get', 'post'], 'search3.view', Search3Controller::class);
        Route::match(['get', 'post'], 'getAlbumList.view', GetAlbumListController::class);
        Route::match(['get', 'post'], 'getAlbumList2.view', GetAlbumList2Controller::class);
        Route::match(['get', 'post'], 'stream.view', StreamController::class);
        Route::match(['get', 'post'], 'getCoverArt.view', GetCoverArtController::class);
        Route::match(['get', 'post'], 'getPlaylists.view', GetPlaylistsController::class);
        Route::match(['get', 'post'], 'getPlaylist.view', GetPlaylistController::class);
        Route::match(['get', 'post'], 'createPlaylist.view', CreatePlaylistController::class);
        Route::match(['get', 'post'], 'updatePlaylist.view', UpdatePlaylistController::class);
        Route::match(['get', 'post'], 'deletePlaylist.view', DeletePlaylistController::class);
        Route::match(['get', 'post'], 'scrobble.view', ScrobbleController::class);
        Route::match(['get', 'post'], 'star.view', StarController::class);
        Route::match(['get', 'post'], 'unstar.view', UnstarController::class);
        Route::match(['get', 'post'], 'setRating.view', SetRatingController::class);
        Route::match(['get', 'post'], 'getStarred.view', GetStarredController::class);
        Route::match(['get', 'post'], 'getStarred2.view', GetStarred2Controller::class);
        Route::match(['get', 'post'], 'getRandomSongs.view', GetRandomSongsController::class);
        Route::match(['get', 'post'], 'getNowPlaying.view', GetNowPlayingController::class);
        Route::match(['get', 'post'], 'getUser.view', GetUserController::class);
        Route::match(['get', 'post'], 'getAvatar.view', GetAvatarController::class);
        Route::match(['get', 'post'], 'getOpenSubsonicExtensions.view', GetOpenSubsonicExtensionsController::class);
        Route::match(['get', 'post'], 'download.view', DownloadController::class);
        Route::match(['get', 'post'], 'getSongsByGenre.view', GetSongsByGenreController::class);
        Route::match(['get', 'post'], 'getLyrics.view', GetLyricsController::class);
        Route::match(['get', 'post'], 'getLyricsBySongId.view', GetLyricsBySongIdController::class);
        Route::match(['get', 'post'], 'getArtistInfo.view', GetArtistInfoController::class);
        Route::match(['get', 'post'], 'getArtistInfo2.view', GetArtistInfo2Controller::class);
        Route::match(['get', 'post'], 'getAlbumInfo.view', GetAlbumInfoController::class);
        Route::match(['get', 'post'], 'getAlbumInfo2.view', GetAlbumInfo2Controller::class);
        Route::match(['get', 'post'], 'getPodcasts.view', GetPodcastsController::class);
        Route::match(['get', 'post'], 'getNewestPodcasts.view', GetNewestPodcastsController::class);
        Route::match(['get', 'post'], 'refreshPodcasts.view', RefreshPodcastsController::class);
        Route::match(['get', 'post'], 'createPodcastChannel.view', CreatePodcastChannelController::class);
        Route::match(['get', 'post'], 'deletePodcastChannel.view', DeletePodcastChannelController::class);
        Route::match(['get', 'post'], 'getPlayQueue.view', GetPlayQueueController::class);
        Route::match(['get', 'post'], 'savePlayQueue.view', SavePlayQueueController::class);
    });
