// List of fonts commonly available on a user's machine.
// This is to be used in case accessing local fonts using local-fonts API fails.

export const genericFonts = [
  'system-ui',
  'sans-serif',
  'serif',
  'monospace',
  'cursive',
  'fantasy',
]

export const commonFonts = [
  'Andale Mono',
  'Arial',
  'BlinkMacSystemFont',
  'Book Antiqua',
  'Caladea',
  'Cambria',
  'Cantarell',
  'Carlito',
  'Consolas',
  'Constantia',
  'Courier New',
  'DejaVu Sans',
  'DejaVu Sans Mono',
  'DejaVu Serif',
  'Droid Sans',
  'Droid Sans Mono',
  'FreeMono',
  'FreeSans',
  'FreeSerif',
  'Geneva',
  'Georgia',
  'Gill Sans',
  'Liberation Mono',
  'Liberation Sans',
  'Liberation Serif',
  'Lucida Console',
  'Lucida Grande',
  'Menlo',
  'Monaco',
  'Nimbus Mono L',
  'Nimbus Roman',
  'Nimbus Sans',
  'Noto Sans',
  'Noto Sans Mono',
  'Noto Serif',
  'Palatino Linotype',
  'Piboto',
  'SF Pro Display',
  'SF Pro Text',
  'San Francisco',
  'Segoe UI',
  'Source Code Pro',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Ubuntu',
  'Ubuntu Mono',
  'Verdana',
]
