name: Frontend Lint
on:
  pull_request:
    branches:
      - master
    paths:
      - resources/assets/**
      - .github/workflows/lint-frontend.yml
  push:
    branches:
      - master
      - next
    paths:
      - resources/assets/**
      - .github/workflows/lint-frontend.yml
  workflow_dispatch:

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
