name: Backend Lint and Static Analysis

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  push:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.3 ]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
      - name: Install PHP dependencies
        uses: ramsey/composer-install@1919f6c305aea6ab10e6181a8ddf72317ad77e0e # 2.3.1
        with:
          composer-options: --prefer-dist
      - name: Run code style checker
        run: composer cs
      - name: Run linter
        run: composer lint
      - name: Run static analysis
        run: composer analyze -- --no-progress
