name: Backend Tests - PostgreSQL

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
  push:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.2 ]
        postgres-version: [ 15 ]
      fail-fast: false
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: koel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_CONNECTION: pgsql-ci
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: koel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 21
      - run: yarn install && yarn build # Needed for Proxy Auth tests
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: pdo_pgsql, zip, gd
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist
      - name: Generate app key
        run: php artisan key:generate --quiet
      - name: Run tests
        run: composer test
        env:
          COMPOSER_PROCESS_TIMEOUT: 600
      - name: Upload logs if broken
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-be-pgsql-logs-${{ github.run_id }}-${{ github.run_attempt }}
          path: storage/logs
