name: Backend Tests - MariaDB

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  push:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.3 ]
        mariadb-version: [ 11.7 ]
      fail-fast: false
    services:
      mariadb:
        image: mariadb:${{ matrix.mariadb-version }}
        env:
          MYSQL_DATABASE: koel
          MYSQL_USER: mariadb
          MYSQL_PASSWORD: mariadb
          MYSQL_ROOT_PASSWORD: mariadb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_CONNECTION: mysql-ci
      DB_HOST: 127.0.1.1
      DB_PORT: 3306
      DB_DATABASE: koel
      DB_USERNAME: root
      DB_PASSWORD: mariadb
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: pdo_mysql, zip, gd
      - name: Install PHP dependencies
        uses: ramsey/composer-install@1919f6c305aea6ab10e6181a8ddf72317ad77e0e # 2.3.1
        with:
          composer-options: --prefer-dist
      - name: Generate app key
        run: php artisan key:generate --quiet
      - name: Run tests
        run: composer test
        env:
          COMPOSER_PROCESS_TIMEOUT: 600
      - name: Upload logs if broken
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: unit-be-mariadb-logs-${{ github.run_id }}-${{ github.run_attempt }}
          path: storage/logs
