name: Backend Tests - SQLite

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  push:
    branches:
      - master
    paths-ignore:
      - resources/assets/**
      - docs/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.2 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug
          extensions: pdo_sqlite, zip, gd
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist
      - name: Generate app key
        run: php artisan key:generate --quiet
      - name: Run tests with coverage
        run: composer coverage
        env:
          COMPOSER_PROCESS_TIMEOUT: 600
      - name: Upload logs if broken
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-be-logs-${{ github.run_id }}-${{ github.run_attempt }}-sqlite
          path: storage/logs
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
